
Pkg.update()

Pkg.add("JuMP")
Pkg.add("Cbc")
Pkg.add("Clp")
Pkg.add("Gadfly")
Pkg.add("SQLite")
Pkg.add("BusinessDays")
Pkg.add("InterestRates")
Pkg.add("DataFrames")
Pkg.add("JSON")
Pkg.add("GZip")
Pkg.add("TimeZones")
Pkg.add("HttpParser")
Pkg.add("Optim")
Pkg.add("Calculus")
Pkg.add("ForwardDiff")
Pkg.add("PyCall")
Pkg.add("TimeSeries")
#Pkg.add("RCall")
